FROM mcr.microsoft.com/devcontainers/base:resolute

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
        ca-certificates \
    && curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \
    && apt-get install -y --no-install-recommends \
        git \
        wget \
        build-essential \
        libssl-dev \
        libreadline-dev \
        zlib1g-dev \
        libyaml-dev \
        libffi-dev \
        ruby \
        ruby-dev \
        unzip \
        nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD ["bash"]